// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bnbHelperGof
Rcpp::List bnbHelperGof(const arma::uvec ancest, const arma::uvec children, const arma::mat& dat, const arma::cube& G, int withinAgg, int aggType, int bs, int intercept);
RcppExport SEXP _cdcs_bnbHelperGof(SEXP ancestSEXP, SEXP childrenSEXP, SEXP datSEXP, SEXP GSEXP, SEXP withinAggSEXP, SEXP aggTypeSEXP, SEXP bsSEXP, SEXP interceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uvec >::type ancest(ancestSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type children(childrenSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dat(datSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type G(GSEXP);
    Rcpp::traits::input_parameter< int >::type withinAgg(withinAggSEXP);
    Rcpp::traits::input_parameter< int >::type aggType(aggTypeSEXP);
    Rcpp::traits::input_parameter< int >::type bs(bsSEXP);
    Rcpp::traits::input_parameter< int >::type intercept(interceptSEXP);
    rcpp_result_gen = Rcpp::wrap(bnbHelperGof(ancest, children, dat, G, withinAgg, aggType, bs, intercept));
    return rcpp_result_gen;
END_RCPP
}
// bnbHelperanm
Rcpp::List bnbHelperanm(const arma::mat ancest, const arma::mat children, const arma::cube& G, int withinAgg, int aggType, int bs, int intercept);
RcppExport SEXP _cdcs_bnbHelperanm(SEXP ancestSEXP, SEXP childrenSEXP, SEXP GSEXP, SEXP withinAggSEXP, SEXP aggTypeSEXP, SEXP bsSEXP, SEXP interceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type ancest(ancestSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type children(childrenSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type G(GSEXP);
    Rcpp::traits::input_parameter< int >::type withinAgg(withinAggSEXP);
    Rcpp::traits::input_parameter< int >::type aggType(aggTypeSEXP);
    Rcpp::traits::input_parameter< int >::type bs(bsSEXP);
    Rcpp::traits::input_parameter< int >::type intercept(interceptSEXP);
    rcpp_result_gen = Rcpp::wrap(bnbHelperanm(ancest, children, G, withinAgg, aggType, bs, intercept));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cdcs_bnbHelperGof", (DL_FUNC) &_cdcs_bnbHelperGof, 8},
    {"_cdcs_bnbHelperanm", (DL_FUNC) &_cdcs_bnbHelperanm, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_cdcs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
