# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bnbHelperMulti <- function(ancest, children, dat, K, aggType, bs, intercept) {
    .Call(`_cdcs_bnbHelperMulti`, ancest, children, dat, K, aggType, bs, intercept)
}

#' Confidence sets for Causal Discovery
#' 
#' Test whether the goodness of fit for a linear model
#'
#' @param dat an n by p matrix of covariates
#' @param Y a vector of length n containin the dependent variable
#' @param K a vector containing integer values greater than 2 which will be used for the test statistic
#' @param aggType 0 is L-inf, 1 is L1, 2 is L1, 3 is all
#' @param bs the number of bootstrap resamples for the null distribution
#' @param intercept 
#' @return Product of v1 and v2
NULL

singleTestcppMulti <- function(dat, Y, K, aggType, bs, intercept) {
    .Call(`_cdcs_singleTestcppMulti`, dat, Y, K, aggType, bs, intercept)
}

exhaustiveHelperMulti <- function(ordered, dat, K, aggType, bs, intercept) {
    .Call(`_cdcs_exhaustiveHelperMulti`, ordered, dat, K, aggType, bs, intercept)
}

