# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bnbHelperGof <- function(ancest, children, dat, G, withinAgg, aggType, bs, intercept) {
    .Call(`_cdcs_bnbHelperGof`, ancest, children, dat, G, withinAgg, aggType, bs, intercept)
}

bnbHelperanm <- function(ancest, children, G, withinAgg, aggType, bs, intercept) {
    .Call(`_cdcs_bnbHelperanm`, ancest, children, G, withinAgg, aggType, bs, intercept)
}

