# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' bnbHelperGof
#' 
#' This function is a helper for the branchAndBound function
#'
#' @param ancest indices of ancestor in the dat matrix
#' @param children indices of children in the dat matrix
#' @param dat n x p matrix with observations
#' @param G an n x k x |ancest| array of where each variable (corresponding to slice) has k test functions 
#' @param  withinAgg indicates which norm to take when combining test statistics within
#'    a variable but across test functions
#' @param aggType indicates which norm to take when combining test statistics across variables
#' @param bs number of bootstrap draws
#' @param intercept should an additional intercept be included?
#' @return 
#' pval: p-value for each child in children
#' @export
bnbHelperGof <- function(ancest, children, dat, G, withinAgg, aggType, bs, intercept) {
    .Call('_cdcs_bnbHelperGof', PACKAGE = 'cdcs', ancest, children, dat, G, withinAgg, aggType, bs, intercept)
}

#' bnbHelperanm
#' 
#' This function is a helper for the branchAndBound_anm function
#' @param ancest matrix of ancestor basis functions
#' @param children matrix of observed children
#' @param G an n x k x |ancest| array of where each variable (corresponding to slice) has k test functions 
#' @param  withinAgg indicates which norm to take when combining test statistics within
#'    a variable but across test functions
#' @param aggType indicates which norm to take when combining test statistics across variables
#' @param bs number of bootstrap draws
#' @param intercept should an additional intercept be included?
#' @return 
#' pval: p-value for each child in children
#' @export
bnbHelperanm <- function(ancest, children, G, withinAgg, aggType, bs, intercept) {
    .Call('_cdcs_bnbHelperanm', PACKAGE = 'cdcs', ancest, children, G, withinAgg, aggType, bs, intercept)
}

